version: "3.0"
services:
  jupyter:
    image: jupyter/tensorflow-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
